apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-user/devsecops-netflix.git'
    targetRevision: main
    path: helm/netflix
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: netflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
