apiVersion: v1
kind: Service
metadata:
  name: {{ include "netflix.fullname" . }}
spec:
  selector:
    app: {{ include "netflix.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
